### ISSUE TITLE
GriefDefender compatibility

### ISSUE THREAD

**Issue by aglarcz** [CoolDCB/PVPToggle#2]
Hi, would it be possible to add GD compatibility so thats claims with disabled pvp are disabled even if player got PvP status on?
Would be great, i am willing to donate for such feature. https://docs.griefdefender.com/API.html

**Comment by CoolDCB** [comment]
> Hi, would it be possible to add GD compatibility so thats claims with disabled pvp are disabled even if player got PvP status on? Would be great, i am willing to donate for such feature. https://docs.griefdefender.com/API.html
If pvp is disabled by another plugin PvpToggle won't force pvp to be enabled, meaning it should already work exactly as you are wanting :)

**Comment by aglarcz** [comment]
Well I already tested it but looks like your plugin is bypassing the pvp flag of the claim.

**Comment by CoolDCB** [comment]
I'll have a look into that for you and get back to you

**Comment by CoolDCB** [comment]
Unfortunately I cannot seem to build the plugin without purchasing it, I did have a look through their code and don't see any reason why it would be overriden by PvpToggle. I'd be happy to look into this further but I don't have too many options unless you can refer me to a Discord/Support Server?

**Comment by CoolDCB** [comment]
After looking into this issue further this appears to be unrelated to PvpToggle and just an issue with the plugin itself
